### ISSUE TITLE
Better error messages for plugins

### ISSUE THREAD

**Issue by IvanSanchez** [lukeed/taskr#145]
I like [gobblejs](https://github.com/gobblejs/gobble). A lot. It's like fly but made for ES5.

One of the features of gobble I like the most is auto-npm-install-ing of gobble plugins, better explained here: https://youtu.be/9NttxOJqb2A?t=851

In other words, if I use gobblejs and want to run a transform through a gobble plugin that is not (yet) installed, I'll get the following:

```
$ gobble
gobble: could not load uglifyjs plugin. Have you installed it? npm install --save-dev gobble-uglifyjs                                                        
install uglifyjs plugin? [y/n] 
```

```
$ fly default
[10:34:9] default failed due to TypeError: this.source(...).uglify is not a function
$
```

Gobble is _helpful_. It tells me what I need to do in order to use the "uglify" plugin, and it will even save me typing `npm install`. Fly is not as helpful - the error is confusing; at this point (following the tutorials) I haven't been told that Fly relies on plugins, and at this point I don't know how to install them.

Please be like gobble. Pretty-print error messages of (potentially) missing plugins so users can learn they need to `npm install --save-dev fly-whatever` when something fails.

**Comment by ghost** [comment]
You are right about that error message. It's not helpful. 

We are going through a major rewrite and a lot of this stuff will be improved.

I wouldn't go as far as creating a prompt for that, but I agree the error message needs to be improved dramatically.

**Comment by lukeed** [comment]
There needs to be better error handling throughout Fly. The one you listed is practically the only one.

I'm with Bucaran tho and don't think auto-installing is a good idea, especially since it is and will be impossible to know what NPM package you'd want when more than one plugin shares the same method name.

For example, would `.uglify` be "fly-uglify" or "fly-uglifyjs"?

Similarly, and I recently ran into this, "fly-nunjucks" was already registered on NPM and seemingly abandoned. I also wanted to use a compiler sequence different than what was used, so I had to do "fly-nunjucks-render."

They are completely different plugins and both expose `.nunjucks` .. and I imagine there will only be more instances of that as time goes on

**Comment by IvanSanchez** [comment]
Yeah, I've had that problem with Gobble - similar plugins like gobble-less and gobble-less-all are not nice.

I wonder if a monorepo for plugins, [like babel does](https://github.com/babel/babel/tree/master/packages), would be a better approach to this problem. At least the fly maintainers could remove abandoned plugins and/or replace them with ""official"" forks.

**Comment by lukeed** [comment]
I don't really believe it to be a problem tho. Like 99% of all other NPM use-cases, I feel one should actually look at the Readme before downloading something they what may or may not end up wanting.

Without getting too far off track, this issue is about improving errors and Bucaran and I both agree on that point.

**Comment by lukeed** [comment]
Mostly added in `2.0` (#218)

Fly will now notify where there is a name conflict. In that event, the secondary copy will be renamed & mounted with that new name. Eg, if two plugins want to use the name `babel`, the second one will be renamed to `babel1`:

```
'babel' was renamed to 'babel1' because its name was taken`
```

Closing for now. Any new plugin-related behavior suggestions should be opened as a new issue.

Thx!
