### ISSUE TITLE
plugin development?

### ISSUE THREAD

**Issue by ralyodio** [lukeed/taskr#146]
Are there any instructions for developing a plugin to add support for an npm module?

I want to convert dot.js to work with fly, but its unclear how you make a module "flyable".

I get the error `.target not found` when I try to chain.

**Comment by lukeed** [comment]
Yes indeed. https://github.com/bucaran/fly/blob/master/docs/README.md#plugins

Good rule of thumb:

If the API method you're wrapping depends on files' **contents**, use a `filter`. And if the API function is _thennable_ / already a Promise, use a `defer`.
Otherwise (aka: your API method wants a files **glob**) nest your plugin directly into the Fly instance, returning `this`.
