### ISSUE TITLE
Support distributed builds?

### ISSUE THREAD

**Issue by Strate** [lukeed/taskr#162]
Hey everyone!
What dou you think about distributed builds? E.g. using node child processes for efficently use multiple cpus?

**Comment by ghost** [comment]
Sounds like a good opportunity to learn about that as well. I wouldn't know where to start. Do you know any projects doing this already that one could learn from?

**Comment by Strate** [comment]
Yes, I know the one :-)
This is [sigh](https://github.com/sighjs/sigh) build tool. Internally it uses [process-pool](https://www.npmjs.com/package/process-pool) library. I think you can reuse ideas from that projects.

**Comment by ghost** [comment]
Oh, sigh, yes I know sigh. Glad to see @ohjames is still actively working on it.

WRT to the distributed builds, we are always open to improvements. If you want to take a stab at it, feel free to send a PR.

@lukeed Do you have any experience w this?

**Comment by insidewhy** [comment]
The process-pool library is pretty cool and easy to use.

**Comment by lukeed** [comment]
I was thinking about this not too long ago...

I'm not familiar with these libraries specifically, but I am familiar with spawning/handling Node processes in general. I was looking at the [subprocess](https://www.npmjs.com/package/subprocess) lib earlier.

As far as I can see, there's only a benefit in spawning `parallel` (aka, "independent") tasks as their own threads, for a single user or single build use-case.

And if this _were_ to make it into Fly, it ought to be either a global flag or a per-task modifier:

``` js
// flyfile.js

// all `parallel` tasks will auto-spawn a process if available
exports.isDistributed = true; 

// or 

exports.scripts = function * () {
  this.isDistributed = true; // this task only
  yield this.source(...)
};

// or expose new `target()` option

exports.images = function * () {
  yield this.source(...).target({
    depth: 1,
    isDistributed: true
  });
};
```

**Comment by insidewhy** [comment]
Yeah it's debatable how much of a benefit you get during incremental updates but there is some benefit in ensuring your main VM instance never gets CPU bound. The initial/complete build can get a huge speedup... especially when you consider things like requiring `babel` alone takes up 700ms of VM time... if you can delegate that to another JS VM then your build process can carry on its initialisation tasks while other processes initialise `babel` and other heavy APIs.

**Comment by insidewhy** [comment]
One other use-case that's pretty good is running tests. The sigh mocha/karma plugins keep two process instances cached with the required state so that when they are trigger the tests can be triggered immediately. If another change is made quickly then it can be passed to the second test process instance while the first is still reinitialising.

**Comment by insidewhy** [comment]
Another cases is what happens if another test run is requested while the tests are still running. Many test frameworks don't provide a way to stop them from running and you have to wait for the existing tests to exit before running the next tests. sigh-mocha/karma kill the processes immediately and run the tests in the already cached second test framework instance.

**Comment by lukeed** [comment]
Yeah -- a lot of this is predicated on the fact that these big, heavy node tools didn't think ahead and bake in this stuff. But I think with AVA, these older dinosaurs will have to either update (and at the very least, support asynchronous behaviors) or risk going extinct...

That said, your points still hold up and maybe something should be done about them in the meantime.

@bucaran This reminds me of our talks on `fly-plugin`... Something like this could be done.
(For everyone else, we're thinking of reworking how plugins are declared, since currently there are 3-4 ways to write a plugin, and each one carries its own behavior. This new method would be a single, unified syntax that handles your desired behavior "behind the scenes")

``` js
this.plugin('pluginName', {
    async: true, 
    threaded: true, // <-- NEW - if true, spawn own subprocess 
    callback: (source, options) => {
      console.log( source.glob ); // files/**/*
      console.log( source.files ); // ['files/a.js', 'files/b.js', ..]
      console.log( source.buffer ); // Buffer stream
      console.log( source.data ); // Buffer.toString()
      console.log( options ); // this.source().pluginName({options})
    }
  })
```

Of course, the `callback` portion can be a third parameter:

``` js
this.plugin('name', {config}, callback);
```

I guess we'd nest the subprocesses within the `_` "global" --- this'd make it easy to keep track of other subprocesses running & access them from within others.

``` js
this._.subprocess.pluginName.kill()
```

**Comment by lukeed** [comment]
@jbucaran I think we can close this & possibly re-open in the future if it ever comes up again.

**Comment by jorgebucaran** [comment]
Yes, please.

EDIT: Sigh.
