### ISSUE TITLE
Changelog for versions above 0.9.1

### ISSUE THREAD

**Issue by novalu** [lukeed/taskr#197]
Hello, 

is it there changelog for versions above 0.9.1 up to current 1.3.1. I don't know whether is safe to update to next major version without checking changelog for possible breaking changes. 

Thank you.

**Comment by lukeed** [comment]
Hi @novalu, 

My bad, I could have sworn that I maintained a Changelog over time -- I guess not.

Here's the PR for 1.0 that has the breaking changes: #147 

The key changes is that `Flyfile.js` now **has** to be lowercase, `flyfile.js`. The flyfile must also be written in native ES5. Check out the [updated example](https://github.com/flyjs/fly#es5) in the readme.

If you would like to continue to write flyfiles with ES6/7 syntax, you must install `fly-esnext` before doing so. There's also [an example of this](https://github.com/flyjs/fly#es2015-and-beyond) in the readme.

Changes after `1.0` have mostly been new internals and/or fixes.

In the meantime, I'll work on getting together a true changelog.

**Comment by lukeed** [comment]
I'm going to close since it's been over a year since 1.0 and roughly 6 months since 2.0... Any existing users will have upgraded by now. 😬 

From now on, I'll be making sure to use the `Releases` tab as an official changelog. It's now a habit that I've been practicing & really find this as the most helpful method.

Sorry about the inconvenience & neglect -- it's 100% my fault. I promise I'll do better in this arena. 👍
