### ISSUE TITLE
Compatibility with gulp

### ISSUE THREAD

**Issue by normanrz** [lukeed/taskr#21]
Just stumbled on this project. I was wondering if compatibility with gulp-plugins is something that is feasible to achieve.

**Comment by TrySound** [comment]
@normanrz I'm not sure it is possible. Gulp plugins is streams. We don't use streams.

**Comment by normanrz** [comment]
I know streams are not at the core of fly. Maybe it's possible to have a slim adapter for vinyl-streams. That could unlock the vast ecosystem of gulp plugins.

**Comment by TrySound** [comment]
@normanrz If this is a possible, it's too difficult and result will be slow. Better use fly api directly.

**Comment by ghost** [comment]
@normanrz This would be a noble enterprise, but now is not the right timing. Fly is going to support async processes soon (in the next release most likely) and we need to improve the docs, write some other critical plugins and of course add tests :smile: 

Fly differs in both philosophy and implementation from gulp, but I am not against using gulp plugins if there is an easy way to integrate them. But, this is unfortunately low priority at the moment.

###### Spinoff

What plugins are the most useful for you? Writing plugins simple in Fly, we also have a [generator](https://github.com/flyjs/generator-fly) too.

**Comment by ghost** [comment]
@normanrz Thanks for bringing this up. 

@all I think gulp is a great project built by a large community that deserves praise, but I think it's a shame than despite having so many collaborators its source code is still IMO a complicated mangle, uses poorly documented dependencies (orchestrator), forces users to deal with complex abstractions like the Vinyl FS, etc. 

Also, streams are only so useful when so many plugins do not support streams. `gulp-buffer` and other poor attempts at mitigating the problem help little. Some plugins do not support streams because their APIs are written in JavaScript, usually in-memory code transformations that process data synchronously. Providing an async interface for a sync transformation only helps so much. 

Fly's model based in generators offers a more flexible architecture for working with concurrency and true async operations, while still presenting a straightforward way to express natively sync operations. 

I believe Fly pushes the community forward by introducing modern feature, tools and promoting a less imperative programming style.

**Comment by iamstarkov** [comment]
I cannot agreed with mess in a code and poorly documented deps, can you show examples?

anyway, I think, then we need something like "fly-gulp — Run gulp tasks from fly" (e.g. [gulp-grunt](https://www.npmjs.com/package/gulp-grunt) and [grunt-gulp](https://www.npmjs.com/package/grunt-gulp))

**Comment by ghost** [comment]
@iamstarkov
`gulp-grunt` | `grunt-gulp` is just crazy, :sob: 

For poor docs I was talking about `orchestrator` and `vinyl-fs`. Trying to figure out how to use these beyond trivial tasks or when writing plugins results in looking through code often. :-1: 

Now, the comparison was against Fly. So, _compared_ to Fly I find gulp is a beautiful and useful, yet messy ball of yarn and has a poorly designed organization specially _since_ gulp it's the result of hundres of devs working together.

#### _Fly_

First there is `bin/index.js` where the root's `index.js` is fetched to `co`. `index.js` is just a few lines of code parsing `process.argv` and acting as the controller for each of the CLI options.

What actually gets to run the tasks is the part where you create the Fly instance and the arguments to this constructor are conveniently computed by `cli.spawn` because we need to both load a `package.json` optionally and plugins and we want to hide the complexity of using a few `try...catch` blocks when we try to `[global.]require(...)` files that could not exist (like `package.json`, etc).

The Fly object / class / module is less than 200 LOC including fair documentation via plenty of comments. This includes the basic IO computations, Fly's prototype, the task runner methods, and the constructor where obvious things such as loading plugins, changing to the root where the Flyfile is, etc., occurs.

Also worth mentioning, Fly extends a very terse _Emitter_ class (a simple pub/sub interface written in less than 10 loc) that injects a `notify` method letting the `reporter.js` be notified for different events and handle output in a non-concerned manner.

### > can you show examples?

Since there are too many to list, I'll go with a few ones from quickly checking `gulp`'s main repo and from what I remember while I was researching for Fly.
- What is exactly happening in [`gulp.js`](https://github.com/gulpjs/gulp/blob/master/bin/gulp.js) and why are chalk invocations all over the place? How is this not separated to its own file? Also, _where are the comments_? Too much mutation, too many variables. When are we going to graduate from this archaic style of programming?
- Where is root's [`index.js`](https://github.com/gulpjs/gulp/blob/master/index.js) loaded? Why is not this a more aptly named module with only gulp`s prototype definitions?
- What is the difference between all this code and [`gulp-cli`](https://github.com/gulpjs/gulp-cli/blob/master/index.js) and why do both share many of the same deps and the code looks so similar? What the hell is going on there?

**Comment by iamstarkov** [comment]
from my perspective, you are a bit overreacting, but I got it, thank you

**Comment by iamstarkov** [comment]
so what do you think about fly-gulp? i think its pretty powerfull idea

**Comment by ghost** [comment]
> from my perspective, you are a bit overreacting, but I got it, thank you

Maybe. I am very emotional when it comes to software. :smile: 

> so what do you think about fly-gulp? i think its pretty powerful idea

It is a powerful idea indeed.
