### ISSUE TITLE
Browserify usage

### ISSUE THREAD

**Issue by girvo** [lukeed/taskr#26]
Hey there,

What would the plan be for using Browserify/Watchify with Fly? Does it require a plugin to work, or will the fact that Browserify supports streams already (see how it works with Gulp OOTB) mean that we could avoid having a wrapper unnecessarily? 

Are there any issues having `import`'s in your Flyfile, specifically for Browserify transformers?

Cheers

**Comment by ghost** [comment]
Good question. I will have an answer as soon as I release 0.2.0

Definitely no wrappers or painful abstractions.

No problem with using require, but I haven't tested using import in a Flyfile. I like this.

**Comment by ghost** [comment]
@girvo Alright, so fly@0.2.0 is out.

Now we have support for async tasks in plugins. 

For example a plugin for browserify _could_ look like this:

``` js
function myFilter (data, options, cb) {
  // do browserify stuff here
}

this.filter("myPlugin", (source, options) => {
  return this.defer(myFilter).call(this, source, options)
})
```

I haven't actually done this as I just bumped this version and I still have some _TODOs_ before I can tackle a browserify plugin.

But with async support this should be possible regardless of how browserify works.

Now, Fly does not use streams so different from gulp in which a browserify plugin would be discouraged, it would be ok in Fly, since it would just be a couple of LOC and we want to integrate nicely into Fly promise sequence.

**Comment by ghost** [comment]
@girvo Now we have a [work around](https://github.com/madcapjake/fly-browserify). It's not perfect as it ends up reading IO twice due to Fly's inability to handle streams at the moment, but this should change when [_channels_](https://github.com/ubolonton/js-csp) land in Fly somewhere around 0.4.0 or 0.5.0

**Comment by ghost** [comment]
@MadcapJake Comments?

**Comment by MadcapJake** [comment]
With the latest [fly-browserify](https://github.com/MadcapJake/fly-browserify), we now have a working implementation.  I for one, am happy with where it's at even with the extra IO because at least it works! :sweat_smile:

Also, with regards to imports, I am currently using [earlify](https://github.com/breuleux/earlify) with it and it works just fine!  You can set all the options that browserify normally accepts too.

As an example, right now I'm working on a `gh-pages` website written entirely in Earl Grey and I'm using fly to build it.  It's really basic right now but it works and I can jump in and uncomment uglify when I'm ready for production (Which is kind of a neat way to think about it as I can jump in to my Flyfile and treat each filter as switches to be turned on and off).  Check it out [here](https://github.com/MadcapJake/earl-academy/tree/gh-pages).

Many thanks to @bucaran for finalizing a proper browserify solution too! :+1:

**Comment by MadcapJake** [comment]
This issue could be closed.  @girvo has contacted me on `fly-browserify`'s repo, we were stuck at a bug but I've written a fix and I'm just waiting to hear back on whether that has fixed it.

**Comment by ghost** [comment]
@MadcapJake Thanks!
