### ISSUE TITLE
What happened to the repo history?

### ISSUE THREAD

**Issue by apkoponen** [lukeed/taskr#277]
Hi,

from the [graph](https://github.com/flyjs/fly/graphs/contributors) it seem like the library would have been largely untouched from late 2015. However, I can see a lot of commits in the [Commits history ](https://github.com/flyjs/fly/commits/master). What's has happened?

**Comment by jorgebucaran** [comment]
EDIT: [**News**](https://github.com/lukeed/taskr/issues/277#issuecomment-311223585). The dispute is settled. Welcome Taskr! 🎉 

---

@apkoponen Hi. The git history was not touched. You can confirm this by cloning github.com/flyjs/fly and looking at the git log. 

The reason @lukeed's contributions are not showing up on GitHub is that **I blocked him** in this organization. This had the unfortunate side effect of hiding his commits from the contributions page. 

His commits are **still** visible [here](https://github.com/flyjs/fly/commits/master?author=lukeed) though.

I would be happy to unblock him if _he_ restores my publishing rights on npm.

I blocked him because he revoked my npm publishing rights on May 20 or 21, 2017 after fighting over how I keep changing the logo of the project.

I've been talking to him for the past several weeks, but he was uncooperative and we were not able to reach an agreement. So, I evicted him from the organization and blocked him.

**Comment by apkoponen** [comment]
Okay, thank you for you thorough answer. Hope you guys can get things solved.

**Comment by jorgebucaran** [comment]
I hope so too!

**Comment by foobarbaz0** [comment]
Not the full story by any means. Quit pushing a narrative that isn't true.

You removed me as an owner of the organization _first_. That, coupled with your declaration to "change or rewrite everything as you see fit," led me to remove your access. It was protective. There was **no doubt** in my mind that you were about to strip my access there, too. The only reason I stayed in the org (demoted) for 2.5 weeks was because we've been in contact with NPM support & it would, of course, look bad if you blocked me from the project right off the bat.

Now, I went back and tried to count the number of times I said "it's not about the logo".... I stopped counting after 32. You keep going back to it because it's the only public-facing manifestation of our dispute.

You're the one who's been uncooperative at every step of the way. And, like now, I'm forced to repeat myself time, and time, and time, and time again. There is no such thing as "compromise" in your mind -- it's either your way or the highway.

I've had to _obey_ your demands left & right. And as soon as I didn't (or spoke up), I was called the combative and uncooperative one. No sir. The logo was just a final [example of your inability to work with people or accept input](https://github.com/flyjs/fly/commit/009e3c037f05abff3d2d2be545ae5890eafae4e2).

Lastly, with all your "big ideas" that would not receive my input, you still haven't done anything to the project except [rewrite history](https://github.com/flyjs/fly/commit/009e3c037f05abff3d2d2be545ae5890eafae4e2)(#272), block me from the org, attack me on Twitter, and plea with NPM to _not only_ handover `fly`, but **all my personal `fly-*` packages** too! Wow.

I guess, at least, it's more than what you've done in the last year and a half.

**Comment by jorgebucaran** [comment]
@foobarbaz and @hzlmn now also banned from the organization for spam. My offer to Luke still stands, restore my publishing rights and I'll unblock you (and your friend).

**Comment by apkoponen** [comment]
I find it quite disturbing that you sensor the other party's opinions so harshly. I only got to see their part of the dispute because I had email notifications on for this thread. 

May I ask why you prevent @foobarbaz0, who I understood was @lukeed's dummy account, from voicing his understanding of the dispute? Open dialogue is the only way I can see a dispute like this could be solved and sensoring other party only makes me feel like you'd have something to hide rather than that you're trying to do the right thing and make things work for the project.

Also, I thought that the issue was just with @lukeed dropping your NPM publishing rights, but now I see other people are also being blocked, even though they did not even comment on this issue?

**Comment by jorgebucaran** [comment]
EDIT: [**News**](https://github.com/lukeed/taskr/issues/277#issuecomment-311223585). The dispute is settled. Welcome Taskr! 🎉 

---

> I thought that the issue was just with @lukeed dropping your NPM publishing rights.

That is why I don't want to discuss any of this on GitHub.

> Open dialogue is the only way I can see a dispute like this could be solved.

I'm all in for open discourse, so do feel free to ping me on twitter/jbucaran and involve the other party if you like. 

EDIT: @hzlmn is one of @lukeed henchmen. I have no more time to waste on this issue.

**Comment by lukeed** [comment]
Unlocked as per @jbucaran's request 🙏

**Comment by jorgebucaran** [comment]
@lukeed Thanks! I say let's keep the history of these issues intact. If people are digging here in the future they might as well get the whole story.

The tone of my posts above shows I was angry at the time I wrote them. People fight and reconcile all the time. We're humans. 

I am happy to announce that Luke and I have settled our differences and decided to do what's best for the project. 

Fly/Taskr was one of my very first open source projects so it is not easy to say this, but it's time to move on. I decided to leave the project and pass it on to Luke who I am sure will do a great job moving forward. 

I'd also like to apologize to @hzlmn. You are not one of Luke's henchmen. Thank you for supporting the project since the very start. Good luck!

Fly is dead, long live Fly. Welcome Taskr! 🎉

**Comment by lukeed** [comment]
Correct 💯 I think it's pretty common to get mixed up in miscommunication and/or misunderstanding -- that's essentially what happened here! The unfortunate part is that it took us a bit too long to realize that _that_ was the issue 😅 

I am [also very pleased](https://twitter.com/lukeed05/status/879072560867983360) to announce that we've arrived at an agreement that we both accept.

@jbucaran appreciates and recognizes my dedication to Fly, and generously offered to transfer the project to me. Of course, I accepted! I look forward to continue working with the existing Fly team members & community whenever the opportunity arises.

Fly will continue its future as Taskr, solely because while all this was happening, I had (and still have) paid work contracts in a production environment that required a stable namespace & future. Unfortunately, with the speed at which some corporations move, it's now "locked in" as Taskr. 

This brings two benefits (1) Taskr will always have a future and (2) Taskr, as a name, marks the beginning of a new chapter in Fly's life.

I'd like to add that Fly is _not_ actually dead. Its inception, motives, and approaches will live on for the duration of this project -- even if only to inspire the next steps! 

So, thank you @jbucaran, for not only entrusting me with the project, but for getting this started in the first place! 🥇 

Good luck with your other projects; they're looking great & are headed on the right track. Looking forward to any visits you may pay us in the future.
