### ISSUE TITLE
No console log when using fly programatically?

### ISSUE THREAD

**Issue by alexandernanberg** [lukeed/taskr#281]
**Background** 
I'm building a tool similar to `next` or `create-react-app` but for  simple websites without react etc. We are currently using gulp but I'd like to replace that with fly. The current code can be found [here](https://github.com/strt/bricks).

**The problem**
I don't seem to be able to get fly to log the expected output when using it programatically. The console is blank but if I run `console.log('whatever')` inside a task that'll show. Am I missing some option? Or is this a intended behaviour? 

**Sample code**
```js
// lib/utils/taskRunner.js
function startTaskRunner() {
  const cwd = path.join(__dirname, '..');
  const file = path.join(cwd, 'flyfile.js');

  const fly = new Fly({
    file,
    cwd,
    plugins: [
      require('fly-clear'),
    ],
  });

  fly.start();
}

startTaskRunner();
```

```js
// lib/flyfile.js
exports.clean = function* (fly) {
  yield fly.clear('dist');
};

exports.default = function* (fly) {
  yield fly.start('clean');
};
```

Thankful for any pointers

**Comment by jorgebucaran** [comment]
@alexandernanberg Hey! I like that plan.

> Am I missing some option? Or is this an intended behavior?

Unfortunately, you can't right now. You can access fly.$.log from a task in your flyfile.js file, but the `fly` instance you get via new Fly() is not attached to the logger/reporter.

I suggest you use console.log() for now. Please watch the repo or follow [@fly__js](https://twitter.com/fly__js) for updates. I plan to revamp fly for 3.0 and among other things, expose the utilities, e.g., the logger, to users.

**Comment by lukeed** [comment]
Hi @alexandernanberg!

Unfortunately, it seems as though you've left us for Gulp 😿 ... but that's okay 😜 

Just wanted to let you know that you could have done this:

```js
const join = require('path').join;
const Taskr = require('taskr');
const Reporter = require('taskr/lib/reporter');

function startTaskRunner() {
  // establish instance
  const taskr = new Taskr({
    cwd: join(__dirname, '..'),
    file: join(cwd, 'taskfile.js'),
    plugins: [
      require('@taskr/clear')
    ],
  });

  // attach Reporter (logger)
  Reporter.call(taskr);

  taskr.start();
}
```

> **Note:** I updated the references from Fly to Taskr since we've changed our name :)

The reason this wasn't done by default (with every instance) is that it's generally not wanted in programmatic use. This is because most of the time, it's used as a silent runner & the main/parent tool is handling is own logging or `stdout` prints.

This follows the same pattern as our main `cli.js` boot script -- [here](https://github.com/lukeed/taskr/blob/master/packages/taskr/cli.js#L24-L25).

Aside from that, as @jbucaran mentioned, the only other option for `logging` is thru each task's first parameter:

```js
exports.default = function * (task) {
  try {
    yield task.source('foo/**').failure({ demo:true });
  } catch (err) {
    task.$.error(`Uh oh! The default task threw: ${err.message}`);
  }
};
```

The full list of inner-task utilities is available [here](https://github.com/lukeed/taskr/tree/master/packages/taskr#utilities)!

Please let me know if that helps and/or you're willing to give Taskr another try 😉 

Thanks!

**Comment by alexandernanberg** [comment]
@lukeed Oh that looks great! I will definitely give Taskr another try, wouldn't be surprised if it replaces gulp now 😉  

Thanks guys 😄

**Comment by lukeed** [comment]
Glad to hear 😄 Feel free to ping me if you have any questions or issues.

PS -- Is it okay to close this now?

**Comment by alexandernanberg** [comment]
Sure, will do! 😄
