### ISSUE TITLE
Hi 👋 is this project still maintained somehow?

### ISSUE THREAD

**Issue by angelogulina** [lukeed/taskr#314]

**Comment by lukeed** [comment]
Hey 👋 It is. It hasn't seen much activity simply due to the fact that it satisfies its functional goals.

There _are_ one or two bugs, but they're being addressed already. I have a 3.0 in the works locally (and have had it for some time), it's just been a lower priority on my TODO list since it is already in working order.

Thanks for making sure!

**Comment by hzlmn** [comment]
> It hasn't seen much activity simply due to the fact that it satisfies its functional goals.

Yep, still use it actively at work and my own projects :P
