### ISSUE TITLE
Abandoned project?

### ISSUE THREAD

**Issue by kytta** [lukeed/taskr#320]
So, I have just stumbled upon this project and I can't help but notice (and wonder) its abandonment. There were no version updates since 2017, the last activity on the repo was back in 2019 (an attempt to bring this project back to life), a lot of PRs are left untouched by either @lukeed or the respective authors (excluding the bizarre #318).

Is there any hope in getting this project back on its feet? I am quite interested in an alternative to Gulp/Grunt, that doesn't have a ton of dependencies while being simple and fast. I am also willing to help with various tasks :)

**Comment by lukeed** [comment]
Not abandoned – stable. You don't need constant noise in order for something to be working.

I have a new major version in the works, but it's not a high priority because of the current stability. And it will include breaking changes (justified) which will require considerable elbow grease in updating the ecosystem at large.

For example, thank you for your PR (#319) but I can't act on it yet because `kleur@3+` requires Node 6.x at minimum, which by itself is a breaking change against the current Node 4.x floor.

In the general case (hopefully), this does not matter, but I know for a fact of some significant users who will be affected by this. 

There's an entire ecosystem at play. Thank you for your concern, but a quick observation doesn't give you an accurate glimpse.

I may start releasing RC updates under a `next` branch (and npm tag) for the ecosystem to begin updating, but it's going to be a slow process. It was the last time around too. FWIW, the WIP version is something like 70% smaller and 50% faster.

**Comment by kytta** [comment]
Ohh, ok, now I get it. Thank you for your explanation 👍
