### ISSUE TITLE
discussion: why Flyfilejs and not flyfile.js?

### ISSUE THREAD

**Issue by iamstarkov** [lukeed/taskr#51]
I prefer gulp, so I will prefer use lowercased filename for fly config

**Comment by ghost** [comment]
Definitely. Either should already work. Otherwise it's a bug.

**Comment by iamstarkov** [comment]
okie, next question, why both filenames are supporting? I think two available options for file will create some problems in the future

**Comment by ghost** [comment]
I prefer Flyfile, but I thought some users might prefer flyfile, that's why.

For example what kind of problems?

**Comment by MadcapJake** [comment]
Check out the [function](https://github.com/flyjs/fly-util/blob/master/src/findPath.js#L13-L21).  I don't really see how having different filenames could cause a problem.  Fly already allows you to specify manually with `-f` so you could technically name your flyfile anything.

**Comment by iamstarkov** [comment]
> For example what kind of problems?

inconsistence is always not good, but prob im a bit paranoid

**Comment by iamstarkov** [comment]
oh

**Comment by iamstarkov** [comment]
also flypath.js is available for everyone. so we already have 4 different names

**Comment by MadcapJake** [comment]
But the only time you use a flyfile is when you run `fly`.  So there's only one place where you'll need to find that file and use it.  There's only one peice of code that is ever used to find the flyfile, too.  I think you'll need to provide a stronger example of an issue that could arise.

**Comment by iamstarkov** [comment]
yep, its not strong, it kinda feeling that something can go wrong. one devs will use Flyfile.js others will flypath.js and everybody will try few times to before found used in project fly config.

**Comment by iamstarkov** [comment]
anyway, we as community will find out how this will work. closing for now

**Comment by ghost** [comment]
@iamstarkov This is a tough one, but I can't see how this could go wrong right now. If you share a `Flypath.js` file with me I will still be able to run it here, because we are using the same `fly` CLI.

To Fly they are all the same. Having it this way lets me use the version I find more tasteful. I believe in the principle of orthogonality (only one way) when writing an API, but in this case I find having multiple permissible versions for the Flyfile a convenient exception.

The way this is handled in the code is flexible enough that if we would ever need to deprecate other names it's just one simple commit without side effects.

**Comment by derhuerst** [comment]
@bucaran

Even though, right now, it doesn't seem like a huge problem, _now_ is the time to fix this. Once fly gains some popularity, it will be an unnecessarily huge effort to convince every plugin author to use the chosen case (`Flyfile` oder `flyfile).

So please act providently and enforce one of the two forms, beginning with the next breaking (non-backwards-compatible) release.

**Comment by MadcapJake** [comment]
@derhuerst but only users have a `Flyfile` not plugin authors.

In fact plugin authors would literally have to do nothing if there was a change to how you can name a flyfile.

Also important to note, gulp allows you to name it capitalized as well.  BrocolliJS defaults to capitalized but allows lowercase.

**Comment by iamstarkov** [comment]
@MadcapJake you are right

**Comment by ghost** [comment]
@derhuerst Thanks for joining the discussion. I am trying to be positive here, but can anybody please explain or just try (no need to be completely accurate) what is exactly the problem of supporting multiple forms of the Flyfile name?

Plugins have _no access_ to how `fly` handles Flyfiles (this is taken care in fly-util), so I don't see any problem there.

Fly plugins are node modules so they can be written in your favorite JavaScript variant if you so wish :smile: 

For example, [`fly-earl`](https://github.com/madcapjake/fly-earl) is written in Earl Grey and it's transpiled to ES5 using `fly` itself, but this is not a requirement and the author is free to use Flyfile.eg, or Flypath.eg. 

I would think this is a nice feature.

**Comment by MadcapJake** [comment]
@bucaran I agree it's a nice feature and in fact it's the precedent for command line tools and especially build automation tools to allow various naming conventions for their required files. Honestly, I think _without_ this feature there'd likely be confusion especially for new users as someone would write the filename upper/lower and then have to figure out why it isn't working.

**Comment by ghost** [comment]
I thought that supporting multiple versions of the Flyfile name would just make users happy as they would be able to choose the name they find more tasteful, if someone can point out how this is a drawback I would be happy to deprecate this functionality, but I still haven't seen a convincing argument.

**Comment by derhuerst** [comment]
Sorry, I meant _developers_ (using fly to build their software) _in general_, not plugin developers. When I was writing, my eye stumbled over the words "plugin" and my brain confused them. :D

So what I actually want to say:

If you enforce a single form now, you can _always_ drop this restriction _later_. But once you allow several forms, you almost can't go back to one form.

This is a bit like npm with their `package.json` `license` field (see npm/npm#8179 and npm/npm#6241). Initially, they accepted packages without a `license` field. Later they decided that this may be bad and now they have warn about thousands of packages in the registry.

I'm not saying that accepting different forms of `flyfile.js` is a bad practice, but that this move makes it difficult to step back from it.

**Comment by ghost** [comment]
> ##### If you enforce a single form now, you can always drop this restriction later. But once you allow several forms, you almost can't go back to one form.
> 
> ##### I'm not saying that accepting different forms of flyfile.js is a bad practice, but that this move makes it difficult to step back from it.

@derhuerst Thanks. Now I understand. I think this is great advice that applies to every single bit of software in general. Regarding this particular issue, we are still on time like you yourself pointed out.

A good rationale as to why or how supporting multiple forms of `flyfile.js` could problematic in the future is needed in order to proceed with this change however.

**Comment by derhuerst** [comment]
What I came up with is actually not a problem regarding different cases of `flyflie.js` but rather another thing to keep in mind.

The native file system of OS X is HFS+. You can set up an HFS+ file system etiher case-sensitive or case-_in_sensitive. OS X works with both, but common software (I'm looking at you, Adobe) breaks if you choose case-sensitive. So in fact, every OS X works case-_in_sensitively.

The implications are as follows: If – at one point in the future – fly will have to check if there are to versions of `flyfile.js`, it might fail because it ends up with the same physical file, accessible under two names (a bit like a hardlink).
