### ISSUE TITLE
Supportting node version

### ISSUE THREAD

**Issue by watilde** [lukeed/taskr#56]
Currently fly supports ["node": ">= 0.11.16"](https://github.com/flyjs/fly/blob/master/package.json#L61), but [co](https://github.com/tj/co) fly are using supports["node": ">= 0.12.0"](https://github.com/tj/co/blob/master/package.json#L32). What do you think about to update supporting version to same version with co?

**Comment by iamstarkov** [comment]
btw, it doesnt work on windows even with node@0.12.7
![screen shot 2015-07-22 at 16 42 08](https://cloud.githubusercontent.com/assets/559321/8828113/ba034726-3090-11e5-9485-af5ae9b22c72.png)

**Comment by ghost** [comment]
@iamstarkov Did you get it to work? #50

**Comment by iamstarkov** [comment]
yep
![screen shot 2015-07-22 at 16 48 40](https://cloud.githubusercontent.com/assets/559321/8828944/ed906b1a-3094-11e5-8704-7d911b5f1e5c.png)

**Comment by ghost** [comment]
@iamstarkov That's very impressive. Does it handle arrow functions too?

**Comment by iamstarkov** [comment]
not sure

**Comment by ghost** [comment]
`--harmony_arrow_functions` should do the trick.

**Comment by iamstarkov** [comment]
btw, everything in a fly can be polyfilled, why fly is not shipping already transpiled?
![screen shot 2015-07-22 at 20 10 32](https://cloud.githubusercontent.com/assets/559321/8833184/cbd61e02-30ad-11e5-94df-b913e044f794.png)

**Comment by ghost** [comment]
@iamstarkov Fly ships transpiled as you can confirm by browsing `dist/`. These flags are used to allow users to write Flyfiles using both generators and arrow functions. This last one is not strictly necessary, but I found it convenient and useful in order to write beautiful Flyfiles.

**Comment by iamstarkov** [comment]
if fly ship itsled already transpiled, then fly should not require any specific node versions.

ability to use arrow functions and generators is in userland and should be fixed by using babel hook with file like _flyfile.babel.js_. If you want es6 just use babel-version of flyfile =)

**Comment by iamstarkov** [comment]
you even dont need co
![screen shot 2015-07-22 at 20 24 11](https://cloud.githubusercontent.com/assets/559321/8833558/a535baf8-30af-11e5-9481-74e73a53489e.png)

**Comment by ghost** [comment]
> if fly ship itsled already transpiled, then fly should not require any specific node versions.

Fly the CLI and task runner is transpiled and does not require any version. But in order to let you write a Flyfile that uses generators we can't support `< 0.11`

### _unless..._

We transpile _every_ `Flyfile` we get our hands on. ATM, we are only transpiling Flyfiles written in ES6/7 or other variants while ES5 are taken just as is (thus running much faster than those written in ES6/7, etc). 

If we were transpiling also ES5 files to support generators, Fly would run for any version of node. The only drawback is that it will still be slow even for those users that are only writing ES5.

This is tough one, perhaps we could control this via a runtime flag.

**Comment by ghost** [comment]
> you even dont need co

We still need to use `co` for the `co-routine` functionality that it provides letting us run tasks concurrently and manipulate generators like state machines out of the box.

Just in case there could be any missunderstanding, `co` has nothing to do with generator support, please see some [examples here](https://github.com/tj/co#examples).

**Comment by derhuerst** [comment]
_IMHO_

I think compiling build scripts on the fly is a bit out of this project's scope. Right now, fly's "selling point" over its competitors is that it fully leverages ES6. This makes fly a nice and lightweight tool for a specific purpose and a specific audience. If fly is going to try to be as universal as other build systems, such as gulp, then it will loose what makes it special.

**Comment by ghost** [comment]
@derhuerst Fly only compiles files written in ES6/7 or other JavaScript variants. If you write ES5 they are processed _untouched_. I know I wrote above we could transpile ES5 files as well to support generators in any version of node, but then we would have to pay the speed penalty. That was in reply to @iamstarkov, and just a suggestion. I am not very keen about that idea TBH.

Now, let me get this straight, are you proposing to _completely_ drop support for ES6/7 and other JavaScript variants? If so, how can users still use Flyfiles written in ES6/7 without dealing with the transpilation themselves.

**Comment by ghost** [comment]
@watilde See tj/co/issues/236

**Comment by MadcapJake** [comment]
@derhuerst right now, fly does transpiling already.  I think this is a great feature that allows me to write flyfiles in Earl Grey (my preferred variant) or ES6/7.  This allows fly to do exactly what you want which is to "fully leverage ES6".  It doesn't do it internally, it uses [js-interpret](https://github.com/tkellen/js-interpret) to import `register` functions that do the compiling for fly.

As far as ES5, the node version and flags, I think we should **not** compile ES5 flyfiles because it's a nice tradeoff: features -> ES6/variants, performance -> ES5.  As a new innovative tool, I think it's important that we push the envelope in terms of pushing node support forward to newer versions rather than eagerly transpiling everything just for supporting all node versions (and also losing performance for ES5 flyfiles).

**Comment by watilde** [comment]
@bucaran Thanks, that changed my mind!

Closing as resolved.

**Comment by ghost** [comment]
@derhuerst This is key

> It (Fly) doesn't do it internally, it uses js-interpret to import register functions (so-called require hooks) that do the (actual) compiling...

The [source is here](https://github.com/flyjs/fly-util/blob/master/src/findPath.js).

Now, if you have any suggestions on how to improve this part (I know this bit is a little complex) I'd love to know. 

I will definitely simplify this at some point!

**Comment by derhuerst** [comment]
> > IMHO
> > 
> > I think compiling build scripts on the fly is a bit out of this project's scope. Right now, fly's "selling point" over its competitors is that it fully leverages ES6. This makes fly a nice and lightweight tool for a specific purpose and a specific audience. If fly is going to try to be as universal as other build systems, such as gulp, then it will loose what makes it special.
> 
> Now, let me get this straight, are you proposing to completely drop support for ES6/7 and other JavaScript variants?

No, I'm not. In fact, I'm urging you to _not do this_. (;

@MadcapJake put it in words I agree with:

> As far as ES5, the node version and flags, I think we should not compile ES5 flyfiles because it's a nice tradeoff: features -> ES6/variants, performance -> ES5.

**Comment by ghost** [comment]
I agree with this too.

> ##### As far as ES5, the node version and flags, I think we should not compile ES5 flyfiles because it's a nice tradeoff: features -> ES6/variants, performance -> ES5.

But bear in mind any significant speed penalty only occurs during the initial compilation of the Flyfile itself. Once that has been transpiled to something we can fetch to node, it should not be dramatically slower than what you would get anyway with plain ES5.

**Comment by ghost** [comment]
0.4.0 will land support for more node versions by registering the require hook! Bonanza!!
