### ISSUE TITLE
flyjs watch task exits after first run

### ISSUE THREAD

**Issue by ontofractal** [lukeed/taskr#63]
Hi, can you help me understand what am I doing wrong? 

```
export default async function () {
  this.watch([paths.scripts], ["build"]);
}

export async function build () {
  await this.clear(paths.lib);
  await this
    .source(paths.scripts)
    .babel({ stage: 1, optional: ["bluebirdCoroutines"] })
    .target(paths.lib);
}
```

Flyjs doesn't continue watching files, though. It executes once on start, then exits. What's wrong with my setup?  I've tried swapping async/await for generators, same results.

I am running iojs 2.4.0 on Ubuntu 15.04 

```
[17:06:13] Flying with .../flyfile.babel.js...
[17:06:13] Starting "default"
[17:06:13] Watching files...
[17:06:13] Starting "build"
[17:06:13] Finished "default" in 6 ms
[17:06:14] Finished "build" in 945 ms
git:(master) ✗ 
```

**Comment by ghost** [comment]
@vdaniuk Hey! I have been able to reproduce this bug.

Somehow chokidar is failing here as well. I have added a new `watch` examples to the `examples/` directory and ill fix in the the next milestone very soon along with several improvements and finally... **tests** :smile:. 

I'll ping you again and sorry for the trouble.

**Comment by ghost** [comment]
@vdaniuk Found and exterminated. The bug was that the latest `fly-util` was not exporting the `watch` function and a silent error was occurring inside the `Fly.start.then` resolve handler.

I have just updated [`fly-util`](https://github.com/flyjs/fly-util) with the fix and as stated earlier, fixes in Fly itself land with fly@0.4.0 :smile: 

Thanks for reporting this.

**Comment by ontofractal** [comment]
Thanks for looking into this, will be waiting for fly@0.4.0!

**Comment by ghost** [comment]
Sure. And btw you should `yield` `this.watch` so that the default `task` waits until the `build` task is finished. This will likely cause no trouble, but it's the right thing to do. Maybe my own examples were faulty, I'll check.

Another petpeeve, arrays you pass into `watch` are flatten and strings are array-fied, so you don't need to enclose `paths.scripts` or `build` in brackets.

**Comment by ghost** [comment]
@vdaniuk I am back and Fly is now fully tested. Please upgrade to [@0.4.0](https://github.com/flyjs/fly/releases) and let me know if you still have any issues.

**Comment by ontofractal** [comment]
@bucaran Everything seems to be working fine now, thanks!

**Comment by ghost** [comment]
Thanks! :+1:
