### ISSUE TITLE
Load plugins lazily

### ISSUE THREAD

**Issue by ghost** [lukeed/taskr#75]
Load plugins only when they are used the first time, and then cache them.

**Comment by iamstarkov** [comment]
lazy load is good idea, caching is probably not. because `require` already has cache implementation

**Comment by ghost** [comment]
Right. My bad. By "caching" I mean loading each plugin only once.

**Comment by iamstarkov** [comment]
what is the reason for that? its already cached on `require` side

**Comment by ghost** [comment]
I was talking about optimizing this bit:

``` js
    plugins.forEach(({ name, plugin }) => {
      plugin.call(this, debug(name.replace("-", ":")))
    })
```

Clearly you are looking at the big picture and talking about optimizing loading plugins at the require level in the CLI. Anyhow, this too should be possible using https://github.com/sindresorhus/lazy-req/

:+1:

**Comment by derhuerst** [comment]
There is a problem about lazy-loading node modules lively instead of ahead of time: Because hrad drives are extremely slow compared to node and it is very defficult to estimate their speed (is it spinning?), a programs performance quickly becomes unreliable. So, AFAIK, it's a common gotcha for big server applications to load _all_ their dependencies right up front.

I know, this is not strictly related to build system, which are heavily disk-bound anyway, but keep that in mind.

**Comment by ghost** [comment]
> is it spinning?

:smile: 

@derhuerst Interesting stuff. I'll definitely keep it in mind.

**Comment by ghost** [comment]
Considered doing this in [@v0.5.0](https://github.com/flyjs/fly/releases/tag/v0.5.0), but didn't find a better excuse than "just for the sake of it". Maybe in the future?

For now I want to work on sourcemaps and other features asap, so I'll close this.
