### ISSUE TITLE
concat should let you specify concat linefeed

### ISSUE THREAD

**Issue by ghost** [lukeed/taskr#99]
I'd love to hear your opinion on the interface @tjbenton.

```
""
"\n"
;
```

And so on.

See #95

**Comment by tjbenton** [comment]
There're a few things that I would find very useful in a concat function.
1. Ability to add a suffix/separator at the end of the file (aka `"\n"`)
2. Ability to add a prefix at the beginning of a file like `;`. This is to prevent plugins from running into each other incase a plugin didn't end with a `;` and the other started with a `(` instead of a `;(` like it should have.
3. For some companies and devs that are inspecting a site being able to know which files/libs are being loaded is very convenient so having a way to to add a header to a file that could add the file name and possibly the version if it's available would be very handy.

Since these things are just optional I would still leave the function alone so you can still just call `this.concat("combined.js")` since that's enough for most devs.

In it's simplest form you should still be able to run it like this.

``` js
export function *js(){
  ...
  yield this.source(...)
          .concat("combined.js")
          .target("dist");
}
```

As for implementing the thoughts above I can see this working in 2 ways

Using an object for the options, all though I don't think this wouldn't be quite as flexible 

``` js
export function *js(){
  ...
  yield this.source(...)
          .uglify()
          .concat("combined.min.js", {
            header: true,
            prefix: ";",
            suffix: "\n"
          })
          .target("dist");
}
```

The header could be the file name it's self

``` js
//! modernizr.js
..the file contents...
```

The second way you could use a callback functions

``` js
export function *js(){
  ...
  yield this.source(...)
          .uglify()
          .concat("combined.min.js", ({data, name, path, ...rest}) => `\n// ${name}\n;${data}\n`)
          .target("dist");
}
```

Using a callback function you can pass in all the available data for the file that you have access to like the name of the file, path, base, dir, etc.

You would also be able to do things like this a lot easier

``` js
const pkg = require("./package.json");

export function *js(){
  ...
  yield this.source(...)
          .uglify()
          .concat("combined.min.js", ({data, name, path, ...rest}) => `\n// ${name}.js\n;${data}\n`)
          .concat("combined.min.js", ({data}) => {
            return `
              // ${pkg.name}
              // ${pkg.author}
              // ${pkg.description}
              ;(function(window, document, undefined){\n
                "use strict";\n
                ${data}
              \n})(window, document);
            `;
          })
          .target("dist");
}
```

This is how I would expect it to output in `dist/combined.min.js`

``` js
// Some package name
// Authors name
// Some long description
;(function(window, document, undefined){
  "use strict";
  // modernizer.js
  ...content for modernizer...
  // lodash.js
  ...content for lodash...

  ...etc
})(window, document);
```

Personally I would prefer using a callback function because it's more flexible, and leaves it up to the developer to do what ever they want to do. Instead of forcing them to do it in one specific way.

The last thing that I would like to see happen is to make it optional to pass in a file name so it would turn the example above into this.

``` js
const pkg = require("./package.json");

export function *js(){
  const combined = "dist/combined.min.js";
  yield this.clear(combined);
  yield this.source(...)
          .uglify()
          .concat(({data, name, path, ...rest}) => `\n// ${name}.js\n;${data}\n`)
          .concat(({data}) => {
            return `
              // ${pkg.name}
              // ${pkg.author}
              // ${pkg.description}
              ;(function(window, document, undefined){\n
                "use strict";\n
                ${data}
              \n})(window, document);
            `;
          })
          .target(combined);
}
```

You would of course have to handle cases where data combined and the `.target(...)` is a directory and not a file name. 

One option is to just default the name of the file in `.combine(...)` to be `combined.[file extention]`.

Another option, and probably easier way would to just throw an error explaining that they have to pass a file name to the target.

Those are my 2 cents :+1:

**Comment by ghost** [comment]
@tjbenton More like 20 dollars! Thanks for laying out all this stuff, it will be useful when implementing this :smile:

**Comment by sylvainpolletvillard** [comment]
With all these options, it would make sense that concat becomes a fly plugin. Then the only function of Fly core API that is actually doing something on the files will be 'filter'. I wonder if a 'reduce' function would be useful for plugins like fly-concat

**Comment by lukeed** [comment]
`fly.concat` will be removed in the `fly@2.0` release. Closing as it's no longer relevant to this repo.

~~(Will update comment with link to `fly-concat` plugin)~~

**Updated:** [`fly-concat`](https://github.com/lukeed/fly-concat)
